#!/usr/bin/env bash

# Function to display information about subdomains
function get_subdomain_info() {
  local domain="$1"
  local subdomain="$2"

  # If subdomain is provided, only show information for that subdomain
  if [[ -n "$subdomain" ]]; then
    dig "$subdomain.$domain" +short | awk -v sd="$subdomain" 'BEGIN {print "ANSWER SECTION:"} {print "The subdomain " sd " is a " $4 " record and points to " $5}'
  else
    # Show information for default subdomains www, lb-01, web-01, and web-02
    dig "www.$domain" +short | awk 'BEGIN {print "ANSWER SECTION:"} {print "The subdomain www is a " $4 " record and points to " $5}'
    dig "lb-01.$domain" +short | awk 'BEGIN {print "ANSWER SECTION:"} {print "The subdomain lb-01 is a " $4 " record and points to " $5}'
    dig "web-01.$domain" +short | awk 'BEGIN {print "ANSWER SECTION:"} {print "The subdomain web-01 is a " $4 " record and points to " $5}'
    dig "web-02.$domain" +short | awk 'BEGIN {print "ANSWER SECTION:"} {print "The subdomain web-02 is a " $4 " record and points to " $5}'
  fi
}

# Call the function with provided arguments
get_subdomain_info "$1" "$2"

