#!/usr/bin/env bash
# installs nginx and nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx

# configure nginx to listen on port 80

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# configure nginx to return 'Hello World!' when queried.

echo 'Hello World' | sudo tee /var/www/html/index.html

# restart nginx so as to apply changes

sudo service nginx restart
