#!/usr/bin/env bash
# This script configures an Nginx web server to redirect requests to the /redirect_me location to a YouTube page with a "301 Moved Permanently" response

# Update package lists
sudo apt-get update

# Install Nginx web server
sudo apt-get install -y nginx

# Allow Nginx traffic through firewall
sudo ufw allow 'Nginx HTTP'

# Set up redirect
REDIRECT_RULE='
    location /redirect_me {
	return 301 https://youtube.com/watch?v=QH2-TGUlwu4;
    }
'
sudo sed -i "/^\s*server_name\s*_/a $REDIRECT_RULE" /etc/nginx/sites-available/default

# Set up landing page
LANDING_PAGE='Hello World!'
echo "$LANDING_PAGE" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restart Nginx
sudo systemctl restart nginx
