#!/usr/bin/env bash
# This script configures an Nginx server to redirect /redirect_me to another page.

# Install nginx if it is not already installed
if ! command -v nginx &> /dev/null; then
  sudo apt-get -y update
  sudo apt-get -y install nginx
fi

# Replace the line with multiple lines in /etc/nginx/sites-available/default
sudo sed -i '/^        location \/ {/a \        location \/redirect_me {\n            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n        }' /etc/nginx/sites
