#!/usr/bin/env bash
# This script Nginx server to have a custom 404 page

# Install nginx if it is not already installed
if ! command -v nginx &> /dev/null; then
  sudo apt-get -y update
  sudo apt-get -y install nginx
fi

echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo sed -i '/server {/a \    error_page 404 /404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
