#!/usr/bin/env bash

# Set variables
TEXT="Hello World!"
REDIRECTRULE="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
FILE="/etc/nginx/sites-available/default"
ERRORFILE="/usr/share/nginx/html/404error.html"
ERRORTEXT="Ceci n'est pas une page\n"
ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\tinternal;\n\t\troot /usr/share/nginx/html;\n\t}\n"
HEADER="\n\tadd_header X-Served-By $HOSTNAME;\n"

# Update package lists and install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Set default page text
echo "$TEXT" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Add redirect rule to configuration file
sudo sed -i "40i\\$REDIRECTRULE" "$FILE"

# Create custom error page
echo "$ERRORTEXT" | sudo tee "$ERRORFILE" > /dev/null

# Add error page redirect to configuration file
sudo sed -i "40i\\$ERRORREDIRECT" "$FILE"

# Add custom header to configuration file
sudo sed -i "40i\\$HEADER" "$FILE"

# Restart nginx to apply changes
sudo service nginx restart
