#!/usr/bin/env bash
# this script displays number 1 to 100

n=1
while (( n <= 100 ))
do
	if (( n % 5 == 0 &  n % 3 == 0 ))
	then
		echo "FizzBuzz"
	elif (( n % 3 == 0 ))
	then
		echo "Fizz"
	elif (( n % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo $n
	fi
	(( i++ ))
done
