#!/usr/bin/env bash
#bash script that displays "Best School" 10 times but displays Hi on the 9th line
n=1

while [ $n -le 10 ]
do
	echo "Best School"
	if [ $n -eq 9 ]
	then
		echo "Hi"
	fi
	n=$(( n + 1 ))
done
