#!/usr/bin/env bash
# this script gives you information about the school file

filename="School"

if [ -e $filename ]
then
	echo "School file exists"
	if [ -s $filrname ]
	then
		echo "School file is not empty"
	fi
	if [-f $filename ]
	then
		echo "School is a regular file"
	fi
else
	excho "School file does not exist"
fi
